services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\TinyMceBundle\EventListener\BeforeRenderTwigTemplateEventListener:
    public: false
    tags:
      - { name: kernel.event_listener, event: huh.twig.beforeRenderTemplate, method: '__invoke' }
