services:
  _defaults:
    autowire: true

  HeimrichHannot\TinyMceBundle\:
    resource: '../../{Manager,Asset}/*'
    public: true

  HeimrichHannot\TinyMceBundle\EventListener\:
    resource: '../../EventListener/Contao/*'
    public: true
