services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\TinyMceBundle\:
    resource: '../../{Asset,EventListener,Manager}/*'

  HeimrichHannot\TinyMceBundle\Asset\FrontendAsset:
    public: true

  HeimrichHannot\TinyMceBundle\Manager\TinyMceManager:
    public: true